const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');
const env = require('../config/env');

const PAGE_MARGIN = 40;
const COLORS = { primary: '#1E3A5F', muted: '#6B7280', line: '#D1D5DB', zebra: '#F3F4F6' };

/** Resolves the institution logo on disk, if one has been uploaded. */
function resolveLogo(logoUrl) {
  if (!logoUrl) return null;
  const key = logoUrl.replace(`${env.storage.publicBaseUrl}/`, '');
  const file = path.resolve(env.storage.localRoot, key);
  return fs.existsSync(file) ? file : null;
}

function drawHeader(doc, { institution = {}, title, subtitle, meta = {} }) {
  const logo = resolveLogo(institution.logoUrl);
  let textX = PAGE_MARGIN;

  if (logo) {
    try {
      doc.image(logo, PAGE_MARGIN, PAGE_MARGIN - 5, { fit: [50, 50] });
      textX = PAGE_MARGIN + 62;
    } catch {
      // A corrupt logo must never break a report.
    }
  }

  doc.fillColor(COLORS.primary).fontSize(15).font('Helvetica-Bold')
    .text(institution.universityName || 'University', textX, PAGE_MARGIN);
  doc.fillColor(COLORS.muted).fontSize(10).font('Helvetica')
    .text(institution.libraryName || 'University Library', textX, doc.y);

  doc.moveDown(0.8);
  doc.fillColor('#111827').fontSize(13).font('Helvetica-Bold').text(title, PAGE_MARGIN, doc.y);
  if (subtitle) {
    doc.fillColor(COLORS.muted).fontSize(9).font('Helvetica').text(subtitle, PAGE_MARGIN, doc.y + 2);
  }

  const metaLine = [
    meta.period ? `Period: ${meta.period}` : null,
    `Generated: ${new Date().toISOString().slice(0, 16).replace('T', ' ')} UTC`,
    meta.generatedBy ? `Generated by: ${meta.generatedBy}` : null,
    meta.total !== undefined ? `Records: ${meta.total}` : null,
    // An export that hit the row ceiling says so instead of looking complete.
    meta.truncatedFrom ? `TRUNCATED: showing ${meta.total} of ${meta.truncatedFrom} matching records` : null,
  ].filter(Boolean).join('    ');
  doc.fillColor(COLORS.muted).fontSize(8).text(metaLine, PAGE_MARGIN, doc.y + 4);

  doc.moveTo(PAGE_MARGIN, doc.y + 6)
    .lineTo(doc.page.width - PAGE_MARGIN, doc.y + 6)
    .strokeColor(COLORS.line).lineWidth(1).stroke();
  doc.moveDown(1);
}

/** Renders a paginated table, repeating the header row on every page. */
function drawTable(doc, columns, rows, options = {}) {
  const usableWidth = doc.page.width - PAGE_MARGIN * 2;
  const totalWeight = columns.reduce((sum, c) => sum + (c.width || 1), 0);
  const widths = columns.map((c) => ((c.width || 1) / totalWeight) * usableWidth);
  const rowHeight = options.rowHeight || 18;

  const renderHeader = () => {
    const y = doc.y;
    doc.rect(PAGE_MARGIN, y, usableWidth, rowHeight).fill(COLORS.primary);
    doc.fillColor('#FFFFFF').fontSize(8).font('Helvetica-Bold');
    let x = PAGE_MARGIN;
    columns.forEach((col, i) => {
      doc.text(String(col.header), x + 4, y + 5, { width: widths[i] - 8, ellipsis: true });
      x += widths[i];
    });
    doc.y = y + rowHeight;
  };

  renderHeader();
  doc.font('Helvetica').fontSize(8);

  rows.forEach((row, index) => {
    if (doc.y + rowHeight > doc.page.height - PAGE_MARGIN - 20) {
      doc.addPage();
      renderHeader();
      doc.font('Helvetica').fontSize(8);
    }
    const y = doc.y;
    if (index % 2 === 1) doc.rect(PAGE_MARGIN, y, usableWidth, rowHeight).fill(COLORS.zebra);

    doc.fillColor('#111827');
    let x = PAGE_MARGIN;
    columns.forEach((col, i) => {
      const raw = row[col.key];
      const value = raw === null || raw === undefined ? '' : String(raw);
      doc.text(value, x + 4, y + 5, {
        width: widths[i] - 8,
        height: rowHeight - 4,
        ellipsis: true,
        align: col.align || 'left',
      });
      x += widths[i];
    });
    doc.y = y + rowHeight;
  });

  if (!rows.length) {
    doc.fillColor(COLORS.muted).fontSize(9)
      .text('No records matched the selected filters.', PAGE_MARGIN, doc.y + 10);
  }
}

/** Adds "Page n of m" to every page. */
function addPageNumbers(doc) {
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i += 1) {
    doc.switchToPage(i);
    doc.fillColor(COLORS.muted).fontSize(8).font('Helvetica')
      .text(
        `Page ${i - range.start + 1} of ${range.count}`,
        PAGE_MARGIN,
        doc.page.height - PAGE_MARGIN + 2,
        { width: doc.page.width - PAGE_MARGIN * 2, align: 'center', lineBreak: false },
      );
  }
}

/**
 * Streams a tabular PDF report to the HTTP response.
 * `columns[].width` is a relative weight, not an absolute size.
 */
function streamTableReport(res, { filename, title, subtitle, institution, meta, columns, rows, landscape = true }) {
  const doc = new PDFDocument({
    size: 'A4',
    layout: landscape ? 'landscape' : 'portrait',
    margin: PAGE_MARGIN,
    bufferPages: true,
    info: { Title: title, Author: institution?.universityName || 'ULMS' },
  });

  if (meta?.truncatedFrom) res.setHeader('X-Export-Truncated', `${rows.length}/${meta.truncatedFrom}`);
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
  doc.pipe(res);

  drawHeader(doc, { institution, title, subtitle, meta: { ...meta, total: rows.length } });
  drawTable(doc, columns, rows);
  addPageNumbers(doc);

  doc.end();
}

/** Starts a free-form document (receipts, certificates) with the standard header. */
function startDocument(res, { filename, title, subtitle, institution, meta, landscape = false, inline = false }) {
  const doc = new PDFDocument({ size: 'A4', layout: landscape ? 'landscape' : 'portrait', margin: PAGE_MARGIN, bufferPages: true });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `${inline ? 'inline' : 'attachment'}; filename="${filename}"`);
  doc.pipe(res);
  drawHeader(doc, { institution, title, subtitle, meta });
  return doc;
}

module.exports = { streamTableReport, startDocument, drawTable, drawHeader, addPageNumbers, PDFDocument, PAGE_MARGIN, COLORS };
